In [9]:
import pickle
with open('data.pickle','rb') as f:
    train,test = pickle.load(f)
cnt = 0
for x in train:
    if x['is entity']=='1':
        cnt+=1
print(cnt,len(train))
cnt = 0
for x in test:
    if x['is entity']=='1':
        cnt+=1
print(cnt,len(test))



532 2330
51 259


In [6]:
import cv2

In [16]:
print('../../webpage-classification/'+train[0]['render'])
img = cv2.imread('../../webpage-classification/'+train[0]['render'])
print(img)

../../webpage-classification/./render/render1344.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[242 242 242]
  [242 242 242]
  [242 242 242]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]

 [[242 242 242]
  [242 242 242]
  [242 242 242]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]

 [[242 242 242]
  [242 242 242]
  [242 242 242]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]]


In [ ]:
%matplotlib inline
from matplotlib import pyplot as plt

for x in train:
    f = plt.imread('../../webpage-classification/'+x['render'])
    if f.shape[0]>f.shape[1]:
        f= f[0:f.shape[1],0:f.shape[1],:]
        #print(x['url'],f.shape)
    plt.imsave('./data/'+x['is entity']+'/'+x['render'],f)
        #plt.imshow(f)
        #plt.show()
        #cv2.imshow(f)
    #print(f.shape)

In [14]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
AUTOTUNE = tf.data.experimental.AUTOTUNE
import IPython.display as display
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import os

import pathlib
#data_dir = tf.keras.utils.get_file(origin='https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
#                                         fname='flower_photos', untar=True)
#data_dir = pathlib.Path(data_dir)

#image_count = len(list(data_dir.glob('*/*.jpg')))

#roses = list(data_dir.glob('roses/*'))

for image in train:
    #image_path = image['render']
    tag = image['is entity']
    if tag=='0':
        tag = "No"
    else:
        tag = "Yes"
    print(tag)
    img = Image.open('../../webpage-classification/'+image_path)
    print(image_path)
    #Image.save()
    #display.display(Image.open('../../webpage-classification/'+image_path['render']))
    #display.display(Image.open(str(image_path)))


No
./render/render1344.png
No
./render/render644.png
No
./render/render209.png


In [11]:
# The 1./255 is to convert from uint8 to float32 in range [0,1].
image_generator = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
BATCH_SIZE = 32
IMG_HEIGHT = 224
IMG_WIDTH = 224
image_count = len(train)
STEPS_PER_EPOCH = np.ceil(image_count/BATCH_SIZE)

In [ ]:
train_data_gen = image_generator.flow_from_directory(directory=str(data_dir),
                                                     batch_size=BATCH_SIZE,
                                                     shuffle=True,
                                                     target_size=(IMG_HEIGHT, IMG_WIDTH),
                                                     classes = list(CLASS_NAMES))

In [2]:
!pip install "tensorflow_hub>=0.6.0"
!pip install "tensorflow>=2.0.0"

import tensorflow as tf
import tensorflow_hub as hub

module_url = "https://tfhub.dev/google/nnlm-en-dim128/2"
embed = hub.KerasLayer(module_url)
embeddings = embed(["A long sentence.", "single-word",
                  "http://example.com"])
print(embeddings.shape)  #(3,128)

     |████████████████████████████████| 92kB 2.6MB/s eta 0:00:011
     |████████████████████████████████| 421.8MB 41kB/s s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/18/90/b77c328a1304437ab1310b463e533fa7689f4bfc41549593056d812fab8e/tensorflow_estimator-2.1.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/b8/83/755bd5324777875e9dff19c2e59daec837d0378c09196634524a3d7269ac/opt_einsum-3.1.0.tar.gz
  Using cached https://files.pythonhosted.org/packages/c3/fd/1e86bc4837cc9a3a5faf3db9b1854aa04ad35b5f381f9648fbe81a6f94e4/google_pasta-0.1.8-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/40/

  Created wheel for opt-einsum: filename=opt_einsum-3.1.0-cp35-none-any.whl size=63904 sha256=2a939d1ef410d9c4ab8c29ef98b2131269ec3e018cad7734248486ddc2ec37f4
  Stored in directory: /root/.cache/pip/wheels/2c/b1/94/43d03e130b929aae7ba3f8d15cbd7bc0d1cb5bb38a5c721833
  Created wheel for gast: filename=gast-0.2.2-cp35-none-any.whl size=7636 sha256=e6b4de4a6197202d3d0048c82f3e00b28f4609e396c892c2e1b11417829e4aff
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
  Created wheel for absl-py: filename=absl_py-0.9.0-cp35-none-any.whl size=119399 sha256=18eb18bcaa1d39aa8f6efeb5c1556a7ab94838cd83797d19ff151e607687dd18
  Stored in directory: /root/.cache/pip/wheels/8e/28/49/fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d
  Created wheel for termcolor: filename=termcolor-1.1.0-cp35-none-any.whl size=5680 sha256=795c6087f4e230fd897020b2ecb7c087d75ac9a5e50d0d666d447cc124f8f41d
  Stored in directory: /root/.cache/pip/wheels/7c/06/54/bc84598b

In [6]:
feature_extractor_url = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2" #@param {type:"string"}

feature_extractor_layer = hub.KerasLayer(feature_extractor_url,
                                         input_shape=(224,224,3))
